INSERT INTO Location.Cities (CityName)
    Values ('London'),
		('Crawley'),
		('Dartford'),
		('Enfield'),
		('Maidenhead'),
		('Slough'),
		('Rochester'),
		('Epsom'),
		('Woking'),
		('Leatherhead'),
		('Bristol'),
		('Portishead'),
		('Keynsham'),
		('Yate'),
		('Thornbury'),
		('Bath'),
		('Patchway'),
		('Filton'),
		('Nailsea'),
		('Weston-super-Mare'),
		('Cardiff'),
		('Penarth'),
		('Barry'),
		('Newport'),
		('Caerphilly'),
		('Risca'),
		('Pontypridd'),
		('Ystrad Mynach'),
		('Cowbridge'),
		('Talbot Green'),
		('Southampton'),
		('Eastleigh'),
		('Winchester'),
		('Salisbury'),
		('Christchurch'),
		('New Milton'),
		('Ringwood'),
		('Fareham'),
		('Portsmouth'),
		('Romsey'),
		('Brighton'),
		('Worthing'),
		('Shoreham-by-Sea'),
		('Eastbourne'),
		('Polegate'),
		('Lewes'),
		('Seaford'),
		('Uckfield'),
		('Haywards Heath'),
		('Burgess Hill'),
		('Plymouth'),
		('Saltash'),
		('Paignton'),
		('Torquay'),
		('Dartmouth'),
		('Ivybridge'),
		('Tavistock'),
		('Okehampton'),
		('Liskeard'),
		('Newton Abbot'),
		('Oxford'),
		('Abingdon'),
		('Bicester'),
		('Woodstock'),
		('Witney'),
		('Faringdon'),
		('Burford'),
		('Aylesbury'),
		('Reading'),
		('Buckingham'),
		('Cambridge'),
		('Stevenage'),
		('Braintree'),
		('Bury St Edmunds'),
		('Mildenhall'),
		('Cambourne'),
		('Ely'),
		('Bedford'),
		('Hitchin'),
		('Bishop''s Stortford');