INSERT INTO Location.Cities (CityName, ClosestCityWithParking)
    Values ('London', 1),
		('Crawley', 1),
		('Dartford', 1),
		('Enfield', 1),
		('Maidenhead', 1),
		('Slough', 1),
		('Rochester', 1),
		('Epsom', 1),
		('Woking', 1),
		('Leatherhead', 1),
		('Bristol', 11),
		('Portishead', 11),
		('Keynsham', 11),
		('Yate', 11),
		('Thornbury', 11),
		('Bath', 11),
		('Patchway', 11),
		('Filton', 11),
		('Nailsea', 11),
		('Weston-super-Mare', 11),
		('Cardiff', 21),
		('Penarth', 21),
		('Barry', 21),
		('Newport', 21),
		('Caerphilly', 21),
		('Risca', 21),
		('Pontypridd', 21),
		('Ystrad Mynach', 21),
		('Cowbridge', 21),
		('Talbot Green', 21),
		('Southampton', 31),
		('Eastleigh', 31),
		('Winchester', 31),
		('Salisbury', 31),
		('Christchurch', 31),
		('New Milton', 31),
		('Ringwood', 31),
		('Fareham', 31),
		('Portsmouth', 31),
		('Romsey', 31),
		('Brighton', 41),
		('Worthing', 41),
		('Shoreham-by-Sea', 41),
		('Eastbourne', 41),
		('Polegate', 41),
		('Lewes', 41),
		('Seaford', 41),
		('Uckfield', 41),
		('Haywards Heath', 41),
		('Burgess Hill', 41),
		('Plymouth', 51),
		('Saltash', 51),
		('Paignton', 51),
		('Torquay', 51),
		('Dartmouth', 51),
		('Ivybridge', 51),
		('Tavistock', 51),
		('Okehampton', 51),
		('Liskeard', 51),
		('Newton Abbot', 51),
		('Oxford', 61),
		('Abingdon', 61),
		('Bicester', 61),
		('Woodstock', 61),
		('Witney', 61),
		('Faringdon', 61),
		('Burford', 61),
		('Aylesbury', 61),
		('Reading', 61),
		('Buckingham', 61),
		('Cambridge', 71),
		('Stevenage', 71),
		('Braintree', 71),
		('Bury St Edmunds', 71),
		('Mildenhall', 71),
		('Cambourne', 71),
		('Ely', 71),
		('Bedford', 71),
		('Hitchin', 71),
		('Bishop''s Stortford', 71);